name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true
        default: 'v1.0.0'

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
            ref: develop

      - name: Create release branch
        run: |
          git checkout -b release/${{ github.event.inputs.version }}
          git push origin release/${{ github.event.inputs.version }}

  mvn-release-prepare:
    runs-on: ubuntu-latest
    needs: create-release-branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: release/${{ github.event.inputs.version }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Configure Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Authenticate with GitHub
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/Cumulocity-IoT/cumulocity-microservice-service-request-mgmt.git

      - name: Run mvn release:prepare
        run: mvn -B release:prepare

  create-pull-request_to_dev:
    runs-on: ubuntu-latest
    needs: mvn-release-prepare
    steps:
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: release/${{ github.event.inputs.version }}
          title: 'Release: Merge release branch to develop'
          body: 'This pull request merges the release branch to the develop branch.'
  
  create-pull-request_to_main:
    runs-on: ubuntu-latest
    needs: create-pull-request_to_dev
    steps:
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: release/${{ github.event.inputs.version }}
          title: 'Release: Merge release branch to main'
          body: 'This pull request merges the release branch to the main branch.'
  
