name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true
        default: 'v1.0.0'

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
            ref: develop

      - name: Create release branch
        run: |
          git checkout -b release/${{ github.event.inputs.version }}
          git push origin release/${{ github.event.inputs.version }}

  mvn-release-prepare:
    runs-on: ubuntu-latest
    needs: create-release-branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: release/${{ github.event.inputs.version }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Configure Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Authenticate with GitHub
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/Cumulocity-IoT/cumulocity-microservice-service-request-mgmt.git

      - name: Run mvn release:prepare
        run: mvn -B release:prepare

  create-released-branch-on-tag:
    runs-on: ubuntu-latest
    needs: mvn-release-prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create released branch from tag
        run: |
          git fetch --tags
          git checkout v${{ github.event.inputs.version }}
          git checkout -b released/${{ github.event.inputs.version }}
          git push origin released/${{ github.event.inputs.version }}

  create-pull-request_to_main:
    runs-on: ubuntu-latest
    needs: create-released-branch-on-tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head: refs/heads/released/${{ github.event.inputs.version }}
          base: main
          title: "Release ${{ github.event.inputs.version }}: Prepare for release."

  create-pull-request_to_dev:
    runs-on: ubuntu-latest
    needs: mvn-release-prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head: refs/heads/release/${{ github.event.inputs.version }}
          base: develop
          title: "Release ${{ github.event.inputs.version }}: Start new iteration."

